#!/bin/bash
xgettext --language=Python --keyword=_ --output=po/emmi-control-parental.pot usr/lib/emmi/emmi-control-parental/control-parental.py --from-code=utf-8
cd po
msgmerge es.po emmi-control-parental.pot -o es.po
msgmerge pt_BR.po emmi-control-parental.pot -o pt_BR.po
